### ISSUE TITLE
Gag removal isn't working in some case

### ISSUE THREAD

**Issue by Giferns** [wopox1337/ChatsAdditions_AMXX#50]
How to reproduce:
1) Connect to server and get gag
2) Disconnect from server, change SteamID
3) Connect again from same IP, so gag will be loaded by IP matching
https://github.com/wopox1337/ChatsAdditions_AMXX/blob/1e4ad05a07a2f1786cde9b9107f4241e36a122ac/amxmodx/scripting/include/ChatAdditions_inc/_SQLite.inc#L127-L128
4) Remove gag
5) Reconnect to server, and you may see that gag is active again.

The problem is that deletion requires both parameters to match
https://github.com/wopox1337/ChatsAdditions_AMXX/blob/1e4ad05a07a2f1786cde9b9107f4241e36a122ac/amxmodx/scripting/include/ChatAdditions_inc/_SQLite.inc#L166-L167

----------------------

When gag loads from table we can get rowid (id) value, so we can use it to remove gag

**Comment by wopox1337** [comment]
Closed by https://github.com/wopox1337/ChatsAdditions_AMXX/pull/67

Now, the gag saves in storage only by AuthID. Target player IP not used for now in any storage. (1.0.0)
